---

- name: check if k3s is already installed /etc/systemd/system/k3s.service
  stat:
    path: /etc/systemd/system/k3s.service
  register: k3s_installed

- name: install and added to cluster if not exist

  command: >-
    /tmp/k3s.sh server --server https://{{ master_ip }}:6443 --tls-san {{lb_ip}}
  environment: 
    K3S_TOKEN: "{{ hostvars[groups['master'][0]]['token'] }}"
    INSTALL_K3S_VERSION: "{{k3s_version}}"
  changed_when: true