---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    # - role: prereq
    - role: download
    # - role: raspberrypi

- hosts: master[0]
  become: yes
  roles:
    - role: k3s/master

- hosts: master[1:]
  become: yes
  serial: 1
  roles:
    - role: k3s/master_node

- hosts: node
  become: yes
  roles:
    - role: k3s/node

- hosts: localhost
  connection: local
  roles:
   - role: postconfig/localhost



#### testing
# - hosts: master
#   become: yes
#   roles:
#     - role: download
#     - role: k3s/master

# - hosts: node
#   become: yes
#   roles:
#     - role: download
#     - role: k3s/node