---
# k3s script install

- name: check if dk3s is already installed /etc/systemd/system/k3s.service
  stat:
    path: /etc/systemd/system/k3s.service
  register: k3s_installed

- name: install k3s
  command: >-
    /tmp/k3s.sh server --cluster-init --tls-san $K3S_TLSSAN --disable servicelb
  environment:
    # K3S_DATASTORE_ENDPOINT: "postgres://k3s:kqG9JzYn3BuJTgr8NPhz5M@192.168.3.103:5432/k3s"
    # K3S_NODE_TAINT: "CriticalAddonsOnly=true:NoExecute" # needs to add --node-taint $K3S_NODE_TAINT to the command to enable taint
    K3S_TLSSAN: "{{lb_ip}}"
    K3S_TOKEN: "K108b3a39c5198998adbedc5fa0b173853c04496188cf5cbb0f9a4072ec39d14a6d::server:c0c788fc75e41db1a6b5e30b15d8f7ef"
    INSTALL_K3S_VERSION: "{{k3s_version}}"
  when: not k3s_installed.stat.exists
  changed_when: true

- name: Wait for node-token
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token

- name: Register node-token file access mode
  stat:
    path: /var/lib/rancher/k3s/server
  register: p

- name: Change file access node-token
  file:
    path: /var/lib/rancher/k3s/server
    mode: "g+rx,o+rx"

- name: Read node-token from master
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token

- name: Store Master node-token
  set_fact:
    token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"

- name: Restore node-token file access
  file:
    path: /var/lib/rancher/k3s/server
    mode: "{{ p.stat.mode }}"


- name: Replace https://localhost:6443 by https://lb-ip:6443
  command: >-
    k3s kubectl config set-cluster default
      --server=https://{{ lb_ip }}:6443
      --kubeconfig ~{{ ansible_user }}/.kube/config
  changed_when: true

- name: copy config to local host
  fetch:
    src: /etc/rancher/k3s/k3s.yaml 
    dest: ~/.kube/config
    flat: yes
