---

- name: check if k3s is already installed /etc/systemd/system/k3s.service
  stat:
    path: /etc/systemd/system/k3s.service
  register: k3s_installed

- name: install and added to cluster if not exist

  command: >-
    /tmp/k3s.sh --server $K3S_URL --tls-san $K3S_TLSSAN
  environment: 
    K3S_URL: "https://{{ master_ip }}:6443"
    K3S_TLSSAN: "{{lb_ip}}"
    K3S_TOKEN: "K108b3a39c5198998adbedc5fa0b173853c04496188cf5cbb0f9a4072ec39d14a6d::server:c0c788fc75e41db1a6b5e30b15d8f7ef"
    # K3S_TOKEN: "{{ hostvars[groups['master'][0]]['token'] }}"
    INSTALL_K3S_VERSION: "{{k3s_version}}"
  changed_when: true
