---

- name: check if k3s is already installed /etc/systemd/system/k3s.service
  stat:
    path: /etc/systemd/system/k3s.service
  register: k3s_installed

- name: install and added to cluster if not exist

  command: >-
    /tmp/k3s.sh
  environment: 
    K3S_URL: "https://{{ master_ip }}:6443"
    K3S_TOKEN: "{{ hostvars[groups['master'][0]]['token'] }}"
  
  changed_when: true

- name: install nfs utils
  package:
    name: nfs-common
    state: present